version: '3.9'

services:
  app: 
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # reflect changes we made in our code to container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"